autoInstallPeers: true

dedupePeerDependents: true

engineStrict: true

packageImportMethod: hardlink

preferFrozenLockfile: true

sideEffectsCache: true

storeDir: ~/.pnpm-store

allowBuilds:
  sharp: true
